[build]
builder      = "NIXPACKS"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand          = "npm start"
healthcheckPath       = "/health"
healthcheckTimeout    = 5
restartPolicyType     = "ON_FAILURE"
restartPolicyMaxRetries = 3
